export const EVENT = {
  DEVICES_UPDATE: "DEVICES_UPDATE",
  LOADER_STATE_UPDATE: "LOADER_STATE_UPDATE",
  MODAL_STATE_UPDATE: "MODAL_STATE_UPDATE",
  REPORTS_UPDATE: "REPORTS_UPDATE",
  SECURITY_STATE_UPDATE: "SECURITY_STATE_UPDATE",
  SIDEBAR_STATE_UPDATE: "SIDEBAR_STATE_UPDATE",
  TASKS_UPDATE: "TASKS_UPDATE",
  USER_UPDATE: "USER_UPDATE",
};
